( This gcode generated by /Applications/EAGLE-7.2.0/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

( This file generated from the board /Users/arminlanghofer/Documents/eagle/arduinosnullzaehler/snullv2.brd )
( This file generated 18.01.15 10:39 )

G21

G90
G00 Z30.0000 
G00 X0 Y0
M03
G04 P0.000000
(File Footer)
G00 Z30.0000 
M05
M02
